### ISSUE TITLE
Error uploading with MZ-N420D NetMD Recorder

### ISSUE THREAD

**Issue by hectorleiva** [asivery/webminidisc#14]
Greetings!

I'm attempting to upload some .mp3 tracks and I have been unsuccessful.

The MD Recorder device that I'm using is the [Sony Walkman MZ-N420D](https://www.minidisc.wiki/equipment/sony/portable/mz-n420d) that is listed on this page: https://www.minidisc.wiki/equipment/sorting/netmd

I've tried on the following Operating Systems/Chrome versions:
- Linux / Chromium (Flatpak) ([followed the instructions here and successfully mounted my MD Recorder](https://www.minidisc.wiki/guides/webminidisc#linux))
- Windows 10 / Chrome ([followed the instructions here and successfully mounted my MD Recorder](https://www.minidisc.wiki/guides/webminidisc#windows)]

I'm able to mount the MD Recorder 👍🏼 
![Screenshot 2023-01-05 200914](https://user-images.githubusercontent.com/3849593/210909742-56f69985-2223-4e7e-bb97-d8d2e8a46ad2.png)

I'm able to load a song into the UI 👍🏼 
![Screenshot 2023-01-05 200933](https://user-images.githubusercontent.com/3849593/210909766-ecfb4bb7-c401-42ef-bf08-b2906d8d0a8a.png)

I'm unable to get pass the recording phase
![Screenshot 2023-01-05 200851](https://user-images.githubusercontent.com/3849593/210909812-c826ac2f-f2f6-45d2-8055-0f579bdc98f5.png)

I checked the console tab and I received this message
![Screenshot 2023-01-05 201738](https://user-images.githubusercontent.com/3849593/210910112-12050fce-d92c-4c0a-83ab-a94564cab711.png)

Warning:
```
DevTools failed to load source map: Could not load content for https://web.minidisc.wiki/worker.min.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
and Error:
```
Error: Rejected - 0a1800080046f003010328ff0001001001ffff00000600003ce701e73818
    at B [as constructor] (netmd-shared-objects.ts:5:9)
    at new B (netmd-shared-objects.ts:17:9)
    at A.<anonymous> (netmd-interface.ts:255:23)
    at 2.83f0643a.chunk.js?__WB_REVISION__=393ff1f3eafc810121e8:2:1008898
    at Object.next (2.83f0643a.chunk.js?__WB_REVISION__=393ff1f3eafc810121e8:2:1009003)
    at I (2.83f0643a.chunk.js?__WB_REVISION__=393ff1f3eafc810121e8:2:1007716)
```

Any help would be greatly appreciated since I've started to try and repair some MD Players and I was hoping to have this NetMD be the main producer of MDs to then play when I travel.

I love the project, what a great usage of the web technologies that are available.

Thanks!

**Comment by hectorleiva** [comment]
I've gotten great help in the MiniDisc.wiki discord and they pointed to attempting to use the SonicStage solution located here: https://www.minidisc.wiki/guides/sonicstagew10 and this worked flawlessly on Windows 10 (natively, not through a VM because I wasn't able to get my NetMD player to register through).

My assumption is that there is a data response from `netmd-shared-objects` that doesn't quite fit with what the software is expecting and it errors out? That's my guess.

**Comment by hectorleiva** [comment]
Issue seems to have resolved itself after:
- I deleted all the drivers off of the NetMD device
- I installed the `WinUSB` driver

![Screenshot 2023-01-14 124144](https://user-images.githubusercontent.com/3849593/212487766-441f1b90-ca46-4de0-b32b-1a9dd5c2eeb9.png)
