### ISSUE TITLE
Can't upload to Sony MDS-JB980

### ISSUE THREAD

**Issue by tomekc** [asivery/webminidisc#52]
My deck seem to be supported, and some functions work properly (like wiping the disc, renaming tracks), but attempts to upload fail with:

```
Error: Rejected - 0a1800080046f00301031292004800000048
    at t [as constructor] (https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1707683)
    at new t (https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1707976)
    at e.<anonymous> (https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1316987)
    at https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1309412
    at Object.next (https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1309517)
    at o (https://webmd.pro/static/js/2.0ba8be20.chunk.js:2:1308230)
```

I have tried different cable, different computer and different disc to get the same result. 

I also tried on command line with `netmd-js@4.1.10` and first time I got the same result, and today was able to upload songs,
but on playback I hear only loud white noise.

I'd be happy to provide more data or try some changes if needed.

**Comment by asivery** [comment]
@tomekc I have good news and bad news.
Bad: You have a damaged device. Most likely the drive was swapped from something like the JB480.
Good: There are two ways to fix this.
1) Use the testing version (https://testing.minidisc.wiki/webminidisc-testing)
2) Manually rewrite the EEPROM with an external programmer. I can help you with that.

When a deck breaks like you described, it forgets its keys (sets all values to 0xFF). The device doesn't know that the data is corrupted though, so it interprets these corrupted bytes as key data. Luckily @Sir68k has managed to derive the keys which would be loaded from that corrupted data, so the testing version detects the corruption, and uses these derived keys.
A permanent fix would be the EEPROM rewrite. If you give me the EEPROM image of your device, I can send you back a fixed version, which you can apply in order to resolve this issue completely.
